[workspace]
members = [
    "proc-macros", "wit/introspection",
]
[package]
name = "make-sys"
authors = ["C2Rust"]
version = "4.4.90"
publish = false
edition = "2021"
autobins = false

[lib]
crate-type = ["staticlib", "rlib"]

[[bin]]
path = "bin/make.rs"
name = "make"

[dependencies]
bitflags = "2.13.0"
blake3 = "1.8.5"
c2rust-bitfields = "0.22.1"
chrono = { version = "0.4", default-features = false, features = ["clock", "std"] }
clap = { version = "4", default-features = false, features = ["std", "error-context", "string"] }
digest = "0.11"
itertools = "0.15"
jj-lib-proc-macros = { path = "proc-macros" }
libc = "0.2"
rustc-hash = "2"
salsa = "0.28"

[dev-dependencies]
insta = { version = "=1.48.0", default-features = false }
