//! End-to-end dependency-graph dump: run the real `make` binary on a real
//! makefile with `MAKERS_DEPGRAPH` set and verify the Mermaid graph it
//! writes (the snapshot `main_0` takes after reading makefiles, snapping
//! deps, and installing rules — right before the update walk).
//!
//! The dumped graph doubles as the committed sample in
//! `docs/depgraph-makefile.md`; regenerate it with
//! `UPDATE_SNAPSHOTS=1 cargo test --test depgraph_dump`.

use std::path::PathBuf;
use std::process::Command;
use std::sync::atomic::{AtomicU32, Ordering};

const RUST_MAKE: &str = env!("CARGO_BIN_EXE_make");

fn manifest_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}

/// A fresh scratch directory per call (unique per pid + counter), so runs
/// never collide; contents are left behind for post-mortem inspection.
fn tempdir() -> PathBuf {
    static COUNTER: AtomicU32 = AtomicU32::new(0);
    let dir = std::env::temp_dir().join(format!(
        "makers-depgraph-{}-{}",
        std::process::id(),
        COUNTER.fetch_add(1, Ordering::Relaxed)
    ));
    std::fs::create_dir_all(&dir).expect("create tempdir");
    dir
}

/// Run the just-built `make` on the depgraph fixture in a scratch dir with
/// `MAKERS_DEPGRAPH` pointing at `dump_name`, and return the dumped graph.
/// `-r` keeps builtin rules out of the graph, `-n` keeps the run
/// side-effect-free; MAKEFLAGS-style env is scrubbed so the snapshot is
/// hermetic.
fn dump_graph(dump_name: &str) -> (String, std::process::ExitStatus) {
    let fixture = manifest_dir().join("tests/fixtures/depgraph.mk");
    let workdir = tempdir();
    std::fs::copy(&fixture, workdir.join("Makefile")).expect("copy fixture");
    // The pattern rule's sources exist, so `-n` walks the whole graph and
    // exits 0 (commands are printed, never run).
    std::fs::write(workdir.join("main.c"), "").expect("write main.c");
    std::fs::write(workdir.join("util.c"), "").expect("write util.c");

    let dump = workdir.join(dump_name);
    let status = Command::new(RUST_MAKE)
        .args(["--no-print-directory", "-r", "-n", "-f", "Makefile"])
        .env("MAKERS_DEPGRAPH", &dump)
        .env_remove("MAKEFLAGS")
        .env_remove("GNUMAKEFLAGS")
        .env_remove("MAKEFILES")
        .current_dir(&workdir)
        .status()
        .expect("spawn make");
    let graph = std::fs::read_to_string(&dump)
        .unwrap_or_else(|err| panic!("dump not written to {}: {err}", dump.display()));
    (graph, status)
}

#[test]
fn real_makefile_dumps_a_mermaid_graph() {
    let (graph, status) = dump_graph("graph.md");
    assert!(status.success(), "make -rn on the fixture should succeed");

    assert!(
        graph.starts_with("```mermaid\nflowchart LR\n"),
        "markdown-fenced mermaid"
    );
    assert!(
        graph.contains("[\"prog\"]"),
        "goal target with a recipe: {graph}"
    );
    assert!(
        graph.contains("[[\"%.o: %.c\"]]"),
        "user pattern rule from the rule db: {graph}"
    );
    assert!(graph.contains(" ==> "), "goal edge from <root>: {graph}");
    assert!(
        graph.contains("-.->|order-only|"),
        "`| outdir` prerequisite: {graph}"
    );
    assert!(
        graph.contains("classDef phony"),
        "outdir is marked .PHONY: {graph}"
    );
    // Prerequisites named but never defined as targets resolve by name hash
    // and keep their dep-learned labels.
    assert!(graph.contains("([\"main.o\"])"), "{graph}");
    assert!(graph.contains("([\"util.o\"])"), "{graph}");

    // The same run must be byte-for-byte reproducible.
    let (again, _) = dump_graph("graph.md");
    assert_eq!(graph, again, "dump is deterministic across runs");
}

#[test]
fn dump_format_follows_extension() {
    let (mmd, _) = dump_graph("graph.mmd");
    assert!(mmd.starts_with("flowchart LR\n"), "raw mermaid: {mmd}");

    let (dot, _) = dump_graph("graph.dot");
    assert!(dot.starts_with("digraph deps {"), "graphviz: {dot}");
    assert!(dot.contains("\"prog\""), "{dot}");
}

/// Committed visualization of the fixture's dump. Fails when stale;
/// regenerate with `UPDATE_SNAPSHOTS=1 cargo test --test depgraph_dump`.
#[test]
fn makefile_snapshot_doc_is_current() {
    let (graph, _) = dump_graph("graph.md");
    let fixture = std::fs::read_to_string(manifest_dir().join("tests/fixtures/depgraph.mk"))
        .expect("fixture readable");

    let doc = format!(
        "# Dependency graph of a real makefile\n\
         \n\
         <!-- Generated by tests/depgraph_dump.rs (makefile_snapshot_doc_is_current). -->\n\
         <!-- Regenerate with: UPDATE_SNAPSHOTS=1 cargo test --test depgraph_dump -->\n\
         \n\
         What the real `make` binary knows right before the update walk, dumped\n\
         via `MAKERS_DEPGRAPH=graph.md make -rn` from this makefile\n\
         (`tests/fixtures/depgraph.mk`):\n\
         \n\
         ```make\n{fixture}```\n\
         \n\
         {graph}"
    );

    let snapshot = manifest_dir().join("docs/depgraph-makefile.md");
    if std::env::var_os("UPDATE_SNAPSHOTS").is_some() {
        std::fs::write(&snapshot, &doc).expect("write snapshot");
        return;
    }
    let committed = std::fs::read_to_string(&snapshot)
        .expect("docs/depgraph-makefile.md exists (UPDATE_SNAPSHOTS=1 to create)");
    assert_eq!(
        committed, doc,
        "docs/depgraph-makefile.md is stale; regenerate with UPDATE_SNAPSHOTS=1"
    );
}
